project:
  type: website

website:
  title: "PODFRIDGEâ€‘Databases"
  navbar:
    left:
      - href: site/index.qmd   # was index.qmd
        text: Home
      - href: site/about.qmd   # was about.qmd
        text: About
      - text: Analyses
        menu:
          - href: analysis/ndis_scraping.qmd
            text: NDIS analysis
          - href: analysis/foia_processing.qmd
            text: FOIA processing

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css     
    toc: true
